server:
  port: 8080



spring:
  profile: local
  application:
    name: cadastro-starters
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/start_db?allowPublicKeyRetrieval=true&sslModel=DISABLED&useSSL=false
    username: root
    password: mauFJcuf5dhRMQrjj
