server:
  port: 8080



spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:start_db;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    username: sa
    password: ricardo
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql=false:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
